// Do not edit. This file is machine generated by the Resource DLL Wizard.

library InspectorBarDemo;

{ITE} {LCID:00000813:00000813} {}
{ITE} {DFMFileType} {UInspectorBarDemo.dfm}
{ITE} {RCFileType} {InspectorBarDemo_DRC.rc}

{$R 'UInspectorBarDemo.dfm' Form1:TForm}
{$R 'InspectorBarDemo_DRC.res' 'InspectorBarDemo_DRC.rc'}

{$E NLB}

begin
end.